// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using AgentStoryComponents.extAPI;
namespace AgentStoryTests
{
    /// <summary>
    ///This is a test class for AgentStoryComponents.extAPI.MyFlikr and is intended
    ///to contain all AgentStoryComponents.extAPI.MyFlikr Unit Tests
    ///</summary>
    [TestClass()]
    public class MyFlikrTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for getMediaMeta (string, bool, int, int)
        ///</summary>
        [TestMethod()]
        public void getMediaMetaTest()
        {
            MyFlikr target = new MyFlikr();

            string UserName = "bukanator"; // TODO: Initialize to an appropriate value

            bool includeEmbedHTML = true; // TODO: Initialize to an appropriate value

            int width = 10; // TODO: Initialize to an appropriate value

            int height = 10; // TODO: Initialize to an appropriate value

            System.Collections.Generic.List<AgentStoryComponents.extAPI.mediaMeta> expected = null;
            System.Collections.Generic.List<AgentStoryComponents.extAPI.mediaMeta> actual;

            actual = target.getMediaMeta(UserName, includeEmbedHTML, width, height);

            Assert.AreEqual(expected, actual, "AgentStoryComponents.extAPI.MyFlikr.getMediaMeta did not return the expected valu" +
                    "e.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }


     
    }


}
